# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", guest: 8787, host: 8787

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    chmod 700 /vagrant/provisioning/*.sh

    /vagrant/provisioning/01-utilities.sh
    /vagrant/provisioning/02-r.sh
    # /vagrant/provisioning/03-sparklyr.sh
    # /vagrant/provisioning/04-tensorflow.sh

    # cp /vagrant/upstarts/*.conf /etc/init/
    # start rstudio

  SHELL
end
